	ORG 0xDA00
BEGIN:		CALL CLS
			CALL HOME
			LXI H, VTIME
			CALL TIME
			LXI H, VDATE
			CALL DATE
			LXI H, VDAY
			CALL DAY
			LXI H, VDATE
			CALL DISPLAY
			CALL CHGET
			CALL INZCOM
			LXI H,RSMSG
LOOP0:		LD A,M
			JP Z,THEEND
			CALL SD232C
			INX H
			JP LOOP0
THEEND:		CALL CLSCOM
			CALL MENU
VDATE:	DS "yy/mm/dd ("
VDAY:	DS "ddd) "
VTIME:	DS "hh:mm:ss "
	DB 13,10
	DS "ENTER KEY:"
	DB 0
RSMSG: DS "Hello"
	DB 0
